"""Full example agent catalog — every kind and capability combination."""

from __future__ import annotations

from typing import Any

from src.models.agent import AgentKind
from src.models.agent_link import AgentLinkType

# Each entry: agent fields + optional nested actions, templates, link_specs (resolved after insert)
FULL_AGENT_CATALOG: list[dict[str, Any]] = [
    # ── One agent per kind (baseline presets) ─────────────────────────────
    {
        "name": "یکپارچه‌ساز API",
        "slug": "example-api-connector",
        "department": "ops",
        "description": "فراخوانی endpointهای یکپارچه‌سازی خارجی به‌عنوان ابزار",
        "kind": AgentKind.CHAT,
        "capabilities": {
            "chat_enabled": True,
            "file_upload_enabled": False,
            "actions_enabled": True,
            "templates_enabled": True,
            "can_call_agents": False,
            "supervisor_enabled": False,
            "external_apis_enabled": True,
        },
        "tool_names": [],
        "api_bind_slugs": {"service": "httpbin-demo", "endpoints": ["get-ip"]},
        "actions": [
            {
                "slug": "check_public_ip",
                "label": "بررسی IP عمومی",
                "prompt_template": "با ابزار HTTPBin IP عمومی را بگیر و خلاصه فارسی بده.",
                "input_schema": {},
                "tool_chain": [],
                "order_index": 0,
            },
        ],
        "templates": [
            {
                "slug": "api_health",
                "label": "سلامت API",
                "body": "وضعیت اتصال به APIهای متصل را بررسی کن.",
                "order_index": 0,
            },
        ],
    },
    {
        "name": "محاسبه‌گر کارکرد",
        "slug": "example-karkard",
        "department": "hr",
        "description": "پردازش فایل اکسل کارکرد ماهانه طبق دستورالعمل HR (سوره)",
        "kind": AgentKind.WORKER,
        "capabilities": {
            "chat_enabled": True,
            "file_upload_enabled": True,
            "actions_enabled": True,
            "templates_enabled": True,
            "can_call_agents": False,
            "supervisor_enabled": False,
        },
        "file_policy": {
            "min_files": 1,
            "max_files": 20,
            "max_file_size_mb": 25,
            "max_total_size_mb": 200,
            "allowed_mime_types": [
                "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                "application/vnd.ms-excel",
                "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            ],
            "allowed_extensions": [".xlsx", ".xls", ".docx"],
            "require_files_to_invoke": False,
            "auto_ingest_to_rag": False,
        },
        "tool_names": ["karkard_process"],
        "config_json": {
            "task_profile": "karkard",
            "instruction_doc": "formdocs/ب/دستور محاسبه کارکرد - cloude.ai.docx",
        },
        "actions": [
            {
                "slug": "process_karkard",
                "label": "محاسبه کارکرد ماهانه",
                "description": "آپلود فایل خام کارکرد را پردازش و فایل نهایی HR تولید می‌کند",
                "prompt_template": "فایل کارکرد آپلودشده را طبق دستورالعمل HR پردازش کن.",
                "input_schema": {
                    "jalali_year": {"title": "سال شمسی", "type": "integer", "default": 1405},
                    "company_name": {
                        "title": "نام شرکت",
                        "type": "string",
                        "default": "شرکت توسعه کارآفرینی سوره",
                    },
                },
                "tool_chain": ["karkard_process"],
                "order_index": 0,
            },
        ],
        "templates": [
            {
                "slug": "karkard_help",
                "label": "راهنمای کارکرد",
                "body": "مراحل محاسبه کارکرد: آپلود اکسل خام → اجرای «محاسبه کارکرد ماهانه» → دانلود خروجی.",
                "order_index": 0,
            },
        ],
    },
    {
        "name": "نمونه گفت‌وگو",
        "slug": "example-chat",
        "department": "ops",
        "description": "Chat-only agent — گفت‌وگو",
        "kind": AgentKind.CHAT,
        "capabilities": {
            "chat_enabled": True,
            "file_upload_enabled": False,
            "actions_enabled": False,
            "templates_enabled": False,
            "can_call_agents": False,
            "supervisor_enabled": False,
        },
        "tool_names": [],
    },
    {
        "name": "نمونه کارگر",
        "slug": "example-worker",
        "department": "finance",
        "description": "Worker — actions + templates, no chat",
        "kind": AgentKind.WORKER,
        "capabilities": {
            "chat_enabled": False,
            "file_upload_enabled": False,
            "actions_enabled": True,
            "templates_enabled": True,
            "can_call_agents": False,
            "supervisor_enabled": False,
        },
        "tool_names": ["hr_lookup", "report_generate"],
        "actions": [
            {
                "slug": "run_payroll",
                "label": "اجرای حقوق",
                "prompt_template": "حقوق دوره {{period}} را آماده کن",
                "input_schema": {"period": {"title": "دوره", "type": "string"}},
                "tool_chain": ["hr_lookup"],
                "order_index": 0,
            },
            {
                "slug": "export_report",
                "label": "گزارش",
                "prompt_template": "گزارش {{report_type}} را تولید کن",
                "input_schema": {"report_type": {"title": "نوع", "type": "string"}},
                "tool_chain": ["report_generate"],
                "order_index": 1,
            },
        ],
        "templates": [
            {
                "slug": "quick_payroll",
                "label": "حقوق سریع",
                "body": "حقوق این ماه را آماده کن",
                "order_index": 0,
            },
        ],
    },
    {
        "name": "نمونه دریافت فایل",
        "slug": "example-file-intake",
        "department": "finance",
        "description": "File intake — upload policy enforced",
        "kind": AgentKind.WORKER,
        "capabilities": {
            "chat_enabled": False,
            "file_upload_enabled": True,
            "actions_enabled": False,
            "templates_enabled": False,
            "can_call_agents": False,
            "supervisor_enabled": False,
        },
        "file_policy": {
            "min_files": 1,
            "max_files": 50,
            "max_file_size_mb": 25,
            "max_total_size_mb": 200,
            "allowed_mime_types": ["application/pdf", "text/plain", "text/csv"],
            "allowed_extensions": [".pdf", ".txt", ".csv"],
            "require_files_to_invoke": False,
            "auto_ingest_to_rag": True,
        },
        "tool_names": [],
    },
    {
        "name": "نمونه سرپرست",
        "slug": "example-supervisor",
        "department": "ops",
        "description": "Supervisor — routes to child agents",
        "kind": AgentKind.SUPERVISOR,
        "capabilities": {
            "chat_enabled": True,
            "file_upload_enabled": False,
            "actions_enabled": False,
            "templates_enabled": False,
            "can_call_agents": False,
            "supervisor_enabled": True,
        },
        "agent_link_policy": {"max_depth": 3, "default_requires_user_permission": False},
        "tool_names": [],
        "link_specs": [
            {"callee_slug": "example-chat", "link_type": AgentLinkType.SUPERVISES},
            {"callee_slug": "example-worker", "link_type": AgentLinkType.SUPERVISES},
            {"callee_slug": "example-file-intake", "link_type": AgentLinkType.SUPERVISES},
        ],
    },
    {
        "name": "نمونه سفارشی",
        "slug": "example-custom",
        "department": "ops",
        "description": "Custom kind — all capabilities enabled",
        "kind": AgentKind.CUSTOM,
        "capabilities": {
            "chat_enabled": True,
            "file_upload_enabled": True,
            "actions_enabled": True,
            "templates_enabled": True,
            "can_call_agents": True,
            "supervisor_enabled": False,
        },
        "file_policy": {
            "min_files": 0,
            "max_files": 20,
            "max_file_size_mb": 10,
            "max_total_size_mb": 100,
            "allowed_mime_types": ["text/plain", "application/pdf"],
            "allowed_extensions": [".txt", ".pdf"],
            "require_files_to_invoke": False,
            "auto_ingest_to_rag": True,
        },
        "tool_names": ["crm_lookup"],
        "actions": [
            {
                "slug": "custom_action",
                "label": "اقدام سفارشی",
                "prompt_template": "{{task}}",
                "input_schema": {"task": {"title": "کار", "type": "string"}},
                "tool_chain": [],
                "order_index": 0,
            },
        ],
        "templates": [
            {"slug": "custom_tpl", "label": "قالب سفارشی", "body": "خلاصه وضعیت را بده", "order_index": 0},
        ],
        "link_specs": [
            {"callee_slug": "example-chat", "link_type": AgentLinkType.TOOL},
        ],
    },
    # ── Capability combinations ───────────────────────────────────────────
    {
        "name": "گفت‌وگو + فایل",
        "slug": "example-chat-files",
        "department": "support",
        "description": "Chat with file upload enabled",
        "kind": AgentKind.CHAT,
        "capabilities": {
            "chat_enabled": True,
            "file_upload_enabled": True,
            "actions_enabled": False,
            "templates_enabled": True,
            "can_call_agents": False,
            "supervisor_enabled": False,
        },
        "file_policy": {
            "min_files": 0,
            "max_files": 10,
            "max_file_size_mb": 5,
            "max_total_size_mb": 25,
            "allowed_mime_types": ["text/plain"],
            "allowed_extensions": [".txt"],
            "require_files_to_invoke": False,
            "auto_ingest_to_rag": False,
        },
        "templates": [
            {"slug": "summarize_ticket", "label": "خلاصه تیکت", "body": "تیکت را خلاصه کن", "order_index": 0},
        ],
        "tool_names": [],
    },
    {
        "name": "کارگر + گفت‌وگو",
        "slug": "example-worker-chat",
        "department": "hr",
        "description": "Worker kind with chat re-enabled",
        "kind": AgentKind.WORKER,
        "capabilities": {
            "chat_enabled": True,
            "file_upload_enabled": False,
            "actions_enabled": True,
            "templates_enabled": True,
            "can_call_agents": False,
            "supervisor_enabled": False,
        },
        "tool_names": ["resume_screen"],
        "actions": [
            {
                "slug": "screen_cv",
                "label": "غربال رزومه",
                "prompt_template": "همه رزومه‌های جدید را برای نقش {{role}} غربال کن و خروجی نهایی بده",
                "input_schema": {"role": {"title": "نقش", "type": "string"}},
                "tool_chain": ["resume_screen"],
                "order_index": 0,
            },
        ],
        "templates": [
            {"slug": "batch_screen", "label": "غربال دسته‌ای", "body": "همه رزومه‌های جدید را غربال کن", "order_index": 0},
        ],
    },
    {
        "name": "ارکستراتور ابزار",
        "slug": "example-orchestrator",
        "department": "ops",
        "description": "Calls other agents as tools",
        "kind": AgentKind.CUSTOM,
        "capabilities": {
            "chat_enabled": True,
            "file_upload_enabled": False,
            "actions_enabled": True,
            "templates_enabled": False,
            "can_call_agents": True,
            "supervisor_enabled": False,
        },
        "agent_link_policy": {"max_depth": 4, "default_requires_user_permission": False},
        "tool_names": [],
        "actions": [
            {
                "slug": "delegate_chat",
                "label": "واگذاری به گفت‌وگو",
                "prompt_template": "از دستیار گفت‌وگو بپرس: {{question}}",
                "input_schema": {"question": {"title": "سوال", "type": "string"}},
                "tool_chain": [],
                "order_index": 0,
            },
        ],
        "link_specs": [
            {"callee_slug": "example-chat", "link_type": AgentLinkType.TOOL},
            {"callee_slug": "example-worker", "link_type": AgentLinkType.TOOL},
        ],
    },
    # ── Department showcase (legacy slugs, richer kinds) ──────────────────
    {
        "name": "دستیار حقوق و دستمزد",
        "slug": "payroll",
        "department": "finance",
        "description": "Monthly payslips, overtime, bank files.",
        "kind": AgentKind.WORKER,
        "capabilities": {
            "chat_enabled": False,
            "file_upload_enabled": False,
            "actions_enabled": True,
            "templates_enabled": True,
            "can_call_agents": False,
            "supervisor_enabled": False,
        },
        "tool_names": ["hr_lookup", "report_generate"],
        "actions": [
            {
                "slug": "generate_payslips",
                "label": "فیش حقوق",
                "prompt_template": "فیش حقوق {{month}} را بساز",
                "input_schema": {"month": {"title": "ماه", "type": "string"}},
                "tool_chain": ["hr_lookup", "report_generate"],
                "order_index": 0,
            },
        ],
        "templates": [
            {"slug": "monthly_payroll", "label": "حقوق ماهانه", "body": "حقوق این ماه را اجرا کن", "order_index": 0},
        ],
    },
    {
        "name": "مغایرت بانکی",
        "slug": "bank-recon",
        "department": "finance",
        "description": "Match bank transactions to ledger.",
        "kind": AgentKind.WORKER,
        "capabilities": {
            "chat_enabled": False,
            "file_upload_enabled": True,
            "actions_enabled": False,
            "templates_enabled": False,
            "can_call_agents": False,
            "supervisor_enabled": False,
        },
        "file_policy": {
            "min_files": 1,
            "max_files": 5,
            "max_file_size_mb": 10,
            "max_total_size_mb": 50,
            "allowed_mime_types": ["text/csv", "application/pdf"],
            "allowed_extensions": [".csv", ".pdf"],
            "require_files_to_invoke": True,
            "auto_ingest_to_rag": True,
        },
        "tool_names": ["report_generate"],
    },
    {
        "name": "صدور فاکتور",
        "slug": "invoice",
        "department": "finance",
        "description": "Bulk invoice generation.",
        "kind": AgentKind.CHAT,
        "capabilities": {
            "chat_enabled": True,
            "file_upload_enabled": False,
            "actions_enabled": True,
            "templates_enabled": True,
            "can_call_agents": False,
            "supervisor_enabled": False,
        },
        "tool_names": ["report_generate"],
        "actions": [
            {
                "slug": "bulk_invoice",
                "label": "فاکتور دسته‌ای",
                "prompt_template": "فاکتورهای {{batch}} را صادر کن",
                "input_schema": {"batch": {"title": "دسته", "type": "string"}},
                "tool_chain": ["report_generate"],
                "order_index": 0,
            },
        ],
        "templates": [
            {
                "slug": "invoice_reminder",
                "label": "یادآوری فاکتور",
                "body": "فاکتورهای معوق را از داده نمونه workspace لیست کن و لینک دانلود گزارش بده",
                "order_index": 0,
            },
        ],
    },
    {
        "name": "غربال رزومه",
        "slug": "resume",
        "department": "hr",
        "description": "CV screening against roles.",
        "kind": AgentKind.WORKER,
        "capabilities": {
            "chat_enabled": False,
            "file_upload_enabled": True,
            "actions_enabled": False,
            "templates_enabled": False,
            "can_call_agents": False,
            "supervisor_enabled": False,
        },
        "file_policy": {
            "min_files": 1,
            "max_files": 100,
            "max_file_size_mb": 5,
            "max_total_size_mb": 200,
            "allowed_mime_types": ["application/pdf", "text/plain"],
            "allowed_extensions": [".pdf", ".txt"],
            "require_files_to_invoke": False,
            "auto_ingest_to_rag": True,
        },
        "tool_names": ["resume_screen"],
    },
    {
        "name": "پاسخ تیکت",
        "slug": "support",
        "department": "support",
        "description": "Classify and respond to tickets.",
        "kind": AgentKind.CHAT,
        "capabilities": {
            "chat_enabled": True,
            "file_upload_enabled": True,
            "actions_enabled": False,
            "templates_enabled": True,
            "can_call_agents": False,
            "supervisor_enabled": False,
        },
        "file_policy": {
            "min_files": 0,
            "max_files": 5,
            "max_file_size_mb": 2,
            "max_total_size_mb": 10,
            "allowed_mime_types": ["text/plain"],
            "allowed_extensions": [".txt"],
            "require_files_to_invoke": False,
            "auto_ingest_to_rag": False,
        },
        "tool_names": [
            "crm_lookup",
            "platform_list_agents",
            "platform_create_agent",
            "platform_generate_widget",
            "platform_ui_action",
        ],
        "templates": [
            {"slug": "close_ticket", "label": "بستن تیکت", "body": "پاسخ پیشنهادی برای بستن تیکت", "order_index": 0},
        ],
    },
    {
        "name": "دستیار عمومی",
        "slug": "general",
        "department": "ops",
        "description": "Multi-purpose enterprise assistant.",
        "kind": AgentKind.CHAT,
        "capabilities": {
            "chat_enabled": True,
            "file_upload_enabled": False,
            "actions_enabled": False,
            "templates_enabled": False,
            "can_call_agents": False,
            "supervisor_enabled": False,
        },
        "tool_names": [],
    },
]

# Backward-compatible demo slugs (redirect to example-* in UI tests)
LEGACY_SLUG_ALIASES = {
    "demo-chat": "example-chat",
    "demo-worker": "example-worker",
    "demo-file-intake": "example-file-intake",
    "demo-supervisor": "example-supervisor",
}
